# Generated by Django 3.0.5 on 2020-04-28 17:55

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archbucket_index_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Value'),
        ),
    ]
