# Generated by Django 3.0.5 on 2020-04-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archbucket_index_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Releases',
            new_name='Release',
        ),
    ]
