# Generated by Django 3.0.5 on 2020-04-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archbucket_index_core', '0002_auto_20200418_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='description',
            field=models.TextField(default='desc', verbose_name='Description'),
        ),
    ]
