# Generated by Django 3.0.5 on 2020-04-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archbucket_index_core', '0003_itemtype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
