# Generated by Django 3.0.5 on 2020-04-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archbucket_index_core', '0004_remove_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.SlugField(default=None, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='url',
            field=models.SlugField(default=None, max_length=150, unique=True),
        ),
    ]
